### ISSUE TITLE
Stuck at press 'play' button and can't start in Windows 10 1709

### ISSUE THREAD

**Issue by vanloc0301** [repeats/Repeat#18] opened 2018-05-08 15:22 UTC
Hi @hptruong93 ,

I have two problem when start Repeat on Windows 10 build 1709.

Information:

> Repeat version: 4.0.1 latest version.
> Windows 10 build 1709.
> JDK 7 updated 79

The first problem:

I tried run Repeat in command line with command: `java -jar Repeat_4_0_1.jar`.

An error appear look like this: 

![capture](https://user-images.githubusercontent.com/4168981/39766035-7b296a7e-530d-11e8-949d-5ce6db712391.PNG)

Error code: 

> Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical

Second:

When click button `recoder` to recoder all action in my screen. When recoder success, I tried to click button `play` to repeat all action but it stuck (don't run anything when I click button `play`).

Hope receive your response with this problem. Thank you very much. 💯

**Comment by hptruong93** [comment] 2018-05-09 00:28
Could you try changing the path to not containing a white space?
Your directory "tool auto" has a white space in it. Try renaming it to tool_auto to see whether the problem disappears.

**Comment by hptruong93** [comment] 2018-05-12 13:51
Confirmed that having space in the path was the cause of the problem.
For the second problem, when recording actions in other programs, you may need appropriate permissions. That is, you may need to run Repeat as administrator in Windows.

**Comment by vanloc0301** [comment] 2018-05-13 11:32
Thanks for first the problem. 
At the second problem, I think to have the problem relate to Windows 10. I receive two response from the user for this problem.

**Comment by hptruong93** [comment] 2018-05-13 18:29
For the second problem, have you tried running it as administrator?
If running from terminal, you'll need to run the terminal as administrator (search for terminal in start menu, right click and choose run as administrator).

**Comment by vanloc0301** [comment] 2018-05-17 06:30
I tried to contact with user in my blog to test. He’s not response my email.
I will comment at this issues when receive email from the user in my blog. 
Thanks @hptruong93

**Comment by neodingo** [comment] 2018-09-01 22:43
Do we understand why the path to the jar cannot contain a space?

**Comment by hptruong93** [comment] 2018-09-01 23:46
There's a URL to URI conversion here
https://github.com/repeats/Repeat/blob/641e7f51996774e9d19e425d7eafa2630de73cd8/src/utilities/FileUtility.java#L562

URI doesn't like space apparently, which caused the exception.

**Comment by hptruong93** [comment] 2019-08-03 16:45
Looks like the problem is because of the space in directory path. I'm going to close this.

**Closed by hptruong93** 2019-08-03 16:45 UTC

**Comment by neodingo** [comment] 2019-08-04 19:14
So we closed a bug due to a space we can't code around in a file path in 2019?  That sounds like a poor decision.
